### PR TITLE
QA Component

### PR DESCRIPTION
**Pull request by avonafaras**
Working on CSS

### CODE REVIEW

**Review by EricBaldwinn — APPROVED** [review]
Looks good for the component parts, remember not to commit your config.js file with your token, this is the reason you have to generate a new token everytime you commit. 
To fix this you can do these commands after you add config.js to gitignore
1. git rm -r --cached .
2. git add .
3. git commit -m 'Removing ignored files'

Also for the merge conflicts I'll look more into them

**Review by EricBaldwinn — CHANGES_REQUESTED** [review]
Sorry, I didn't see the merge conflicts for 
client/dist/bundle.js
client/dist/bundle.js.map
client/src/components/app.jsx
config.js
server/controllers/controllers.js

You will need to make sure your config.js is gitignored and for the client bundle you might need to either figure out what is the issue (what did you install that conflicts I'll look into it) Also i had the same issue with one of my mine and ended up deleting the entire bundle js/map and merging without those not sure if this is the fix here

**Comment by avonafaras** [comment]
Eric thanks for reviewing my PR. Looks like I resolved all the conflicts. I deleted bundle.js and bundle.js.map since they are generated by webpack.  Could you please check it

**Review by beezymc — APPROVED** [review]
I skimmed through the code and nothing looked amiss (as Eric also noted), so I'll be merging this pull request!

**Pull request merged**
